[2024-12-11T17:08:23.168+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-11T17:08:23.193+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_orchestrator.test_connection.dbt_test_connection scheduled__2024-12-11T16:45:00+00:00 [queued]>
[2024-12-11T17:08:23.200+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_orchestrator.test_connection.dbt_test_connection scheduled__2024-12-11T16:45:00+00:00 [queued]>
[2024-12-11T17:08:23.200+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-11T17:08:23.212+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): test_connection.dbt_test_connection> on 2024-12-11 16:45:00+00:00
[2024-12-11T17:08:23.218+0000] {standard_task_runner.py:63} INFO - Started process 473 to run task
[2024-12-11T17:08:23.220+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_orchestrator', 'test_connection.dbt_test_connection', 'scheduled__2024-12-11T16:45:00+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp0acl906p']
[2024-12-11T17:08:23.222+0000] {standard_task_runner.py:91} INFO - Job 54: Subtask test_connection.dbt_test_connection
[2024-12-11T17:08:23.267+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_orchestrator.test_connection.dbt_test_connection scheduled__2024-12-11T16:45:00+00:00 [running]> on host 49f8df2c9427
[2024-12-11T17:08:23.348+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ma7moud' AIRFLOW_CTX_DAG_ID='dbt_orchestrator' AIRFLOW_CTX_TASK_ID='test_connection.dbt_test_connection' AIRFLOW_CTX_EXECUTION_DATE='2024-12-11T16:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-11T16:45:00+00:00'
[2024-12-11T17:08:23.349+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-11T17:08:23.360+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-11T17:08:23.361+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt debug --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt/ecommerce']
[2024-12-11T17:08:23.373+0000] {subprocess.py:86} INFO - Output:
[2024-12-11T17:08:25.765+0000] {subprocess.py:93} INFO - [0m17:08:25  Running with dbt=1.8.0
[2024-12-11T17:08:25.776+0000] {subprocess.py:93} INFO - [0m17:08:25  dbt version: 1.8.0
[2024-12-11T17:08:25.777+0000] {subprocess.py:93} INFO - [0m17:08:25  python version: 3.9.19
[2024-12-11T17:08:25.777+0000] {subprocess.py:93} INFO - [0m17:08:25  python path: /home/***/.local/bin/python
[2024-12-11T17:08:25.778+0000] {subprocess.py:93} INFO - [0m17:08:25  os info: Linux-6.8.0-49-generic-x86_64-with-glibc2.36
[2024-12-11T17:08:25.847+0000] {subprocess.py:93} INFO - [0m17:08:25  Using profiles dir at /opt/***/dbt
[2024-12-11T17:08:25.847+0000] {subprocess.py:93} INFO - [0m17:08:25  Using profiles.yml file at /opt/***/dbt/profiles.yml
[2024-12-11T17:08:25.848+0000] {subprocess.py:93} INFO - [0m17:08:25  Using dbt_project.yml file at /opt/***/dbt/ecommerce/dbt_project.yml
[2024-12-11T17:08:25.848+0000] {subprocess.py:93} INFO - [0m17:08:25  adapter type: postgres
[2024-12-11T17:08:25.849+0000] {subprocess.py:93} INFO - [0m17:08:25  adapter version: 1.8.0
[2024-12-11T17:08:25.933+0000] {subprocess.py:93} INFO - [0m17:08:25  [[33mWARNING[0m]: Deprecated functionality
[2024-12-11T17:08:25.934+0000] {subprocess.py:93} INFO - The `tests` config has been renamed to `data_tests`. Please see
[2024-12-11T17:08:25.934+0000] {subprocess.py:93} INFO - https://docs.getdbt.com/docs/build/data-tests#new-data_tests-syntax for more
[2024-12-11T17:08:25.934+0000] {subprocess.py:93} INFO - information.
[2024-12-11T17:08:25.982+0000] {subprocess.py:93} INFO - [0m17:08:25  Configuration:
[2024-12-11T17:08:25.982+0000] {subprocess.py:93} INFO - [0m17:08:25    profiles.yml file [[32mOK found and valid[0m]
[2024-12-11T17:08:25.983+0000] {subprocess.py:93} INFO - [0m17:08:25    dbt_project.yml file [[32mOK found and valid[0m]
[2024-12-11T17:08:25.983+0000] {subprocess.py:93} INFO - [0m17:08:25  Required dependencies:
[2024-12-11T17:08:25.994+0000] {subprocess.py:93} INFO - [0m17:08:25   - git [[32mOK found[0m]
[2024-12-11T17:08:25.995+0000] {subprocess.py:93} INFO - 
[2024-12-11T17:08:25.995+0000] {subprocess.py:93} INFO - [0m17:08:25  Connection:
[2024-12-11T17:08:25.996+0000] {subprocess.py:93} INFO - [0m17:08:25    host: 172.18.0.3
[2024-12-11T17:08:25.996+0000] {subprocess.py:93} INFO - [0m17:08:25    port: 5432
[2024-12-11T17:08:25.997+0000] {subprocess.py:93} INFO - [0m17:08:25    user: ***
[2024-12-11T17:08:25.997+0000] {subprocess.py:93} INFO - [0m17:08:25    database: ecommerce
[2024-12-11T17:08:25.998+0000] {subprocess.py:93} INFO - [0m17:08:25    schema: oltp
[2024-12-11T17:08:25.998+0000] {subprocess.py:93} INFO - [0m17:08:25    connect_timeout: 10
[2024-12-11T17:08:25.999+0000] {subprocess.py:93} INFO - [0m17:08:25    role: None
[2024-12-11T17:08:25.999+0000] {subprocess.py:93} INFO - [0m17:08:25    search_path: None
[2024-12-11T17:08:26.000+0000] {subprocess.py:93} INFO - [0m17:08:26    keepalives_idle: 0
[2024-12-11T17:08:26.000+0000] {subprocess.py:93} INFO - [0m17:08:26    sslmode: None
[2024-12-11T17:08:26.001+0000] {subprocess.py:93} INFO - [0m17:08:26    sslcert: None
[2024-12-11T17:08:26.001+0000] {subprocess.py:93} INFO - [0m17:08:26    sslkey: None
[2024-12-11T17:08:26.002+0000] {subprocess.py:93} INFO - [0m17:08:26    sslrootcert: None
[2024-12-11T17:08:26.002+0000] {subprocess.py:93} INFO - [0m17:08:26    application_name: dbt
[2024-12-11T17:08:26.003+0000] {subprocess.py:93} INFO - [0m17:08:26    retries: 1
[2024-12-11T17:08:26.004+0000] {subprocess.py:93} INFO - [0m17:08:26  Registered adapter: postgres=1.8.0
[2024-12-11T17:08:26.174+0000] {subprocess.py:93} INFO - [0m17:08:26    Connection test: [[32mOK connection ok[0m]
[2024-12-11T17:08:26.175+0000] {subprocess.py:93} INFO - 
[2024-12-11T17:08:26.175+0000] {subprocess.py:93} INFO - [0m17:08:26  [32mAll checks passed![0m
[2024-12-11T17:08:27.322+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-12-11T17:08:27.323+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-11T17:08:27.349+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dbt_orchestrator, task_id=test_connection.dbt_test_connection, run_id=scheduled__2024-12-11T16:45:00+00:00, execution_date=20241211T164500, start_date=20241211T170823, end_date=20241211T170827
[2024-12-11T17:08:27.406+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-12-11T17:08:27.455+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-11T17:08:27.457+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
