[2024-12-12T08:15:00.769+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-12T08:15:00.791+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_orchestrator.test_connection.dbt_test_connection scheduled__2024-12-12T08:00:00+00:00 [queued]>
[2024-12-12T08:15:00.802+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_orchestrator.test_connection.dbt_test_connection scheduled__2024-12-12T08:00:00+00:00 [queued]>
[2024-12-12T08:15:00.803+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-12T08:15:00.818+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): test_connection.dbt_test_connection> on 2024-12-12 08:00:00+00:00
[2024-12-12T08:15:00.824+0000] {standard_task_runner.py:63} INFO - Started process 417 to run task
[2024-12-12T08:15:00.827+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_orchestrator', 'test_connection.dbt_test_connection', 'scheduled__2024-12-12T08:00:00+00:00', '--job-id', '166', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp5yg35d4c']
[2024-12-12T08:15:00.828+0000] {standard_task_runner.py:91} INFO - Job 166: Subtask test_connection.dbt_test_connection
[2024-12-12T08:15:00.876+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_orchestrator.test_connection.dbt_test_connection scheduled__2024-12-12T08:00:00+00:00 [running]> on host 34fdc836a0bb
[2024-12-12T08:15:00.969+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ma7moud' AIRFLOW_CTX_DAG_ID='dbt_orchestrator' AIRFLOW_CTX_TASK_ID='test_connection.dbt_test_connection' AIRFLOW_CTX_EXECUTION_DATE='2024-12-12T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-12T08:00:00+00:00'
[2024-12-12T08:15:00.970+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-12T08:15:00.985+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-12T08:15:00.986+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt debug --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt/ecommerce']
[2024-12-12T08:15:01.001+0000] {subprocess.py:86} INFO - Output:
[2024-12-12T08:15:03.107+0000] {subprocess.py:93} INFO - [0m08:15:03  Running with dbt=1.8.0
[2024-12-12T08:15:03.120+0000] {subprocess.py:93} INFO - [0m08:15:03  dbt version: 1.8.0
[2024-12-12T08:15:03.121+0000] {subprocess.py:93} INFO - [0m08:15:03  python version: 3.9.19
[2024-12-12T08:15:03.121+0000] {subprocess.py:93} INFO - [0m08:15:03  python path: /home/***/.local/bin/python
[2024-12-12T08:15:03.122+0000] {subprocess.py:93} INFO - [0m08:15:03  os info: Linux-6.8.0-49-generic-x86_64-with-glibc2.36
[2024-12-12T08:15:03.193+0000] {subprocess.py:93} INFO - [0m08:15:03  Using profiles dir at /opt/***/dbt
[2024-12-12T08:15:03.193+0000] {subprocess.py:93} INFO - [0m08:15:03  Using profiles.yml file at /opt/***/dbt/profiles.yml
[2024-12-12T08:15:03.194+0000] {subprocess.py:93} INFO - [0m08:15:03  Using dbt_project.yml file at /opt/***/dbt/ecommerce/dbt_project.yml
[2024-12-12T08:15:03.195+0000] {subprocess.py:93} INFO - [0m08:15:03  adapter type: postgres
[2024-12-12T08:15:03.195+0000] {subprocess.py:93} INFO - [0m08:15:03  adapter version: 1.8.0
[2024-12-12T08:15:03.328+0000] {subprocess.py:93} INFO - [0m08:15:03  Configuration:
[2024-12-12T08:15:03.329+0000] {subprocess.py:93} INFO - [0m08:15:03    profiles.yml file [[32mOK found and valid[0m]
[2024-12-12T08:15:03.330+0000] {subprocess.py:93} INFO - [0m08:15:03    dbt_project.yml file [[32mOK found and valid[0m]
[2024-12-12T08:15:03.331+0000] {subprocess.py:93} INFO - [0m08:15:03  Required dependencies:
[2024-12-12T08:15:03.342+0000] {subprocess.py:93} INFO - [0m08:15:03   - git [[32mOK found[0m]
[2024-12-12T08:15:03.342+0000] {subprocess.py:93} INFO - 
[2024-12-12T08:15:03.343+0000] {subprocess.py:93} INFO - [0m08:15:03  Connection:
[2024-12-12T08:15:03.343+0000] {subprocess.py:93} INFO - [0m08:15:03    host: 172.18.0.3
[2024-12-12T08:15:03.344+0000] {subprocess.py:93} INFO - [0m08:15:03    port: 5432
[2024-12-12T08:15:03.344+0000] {subprocess.py:93} INFO - [0m08:15:03    user: ***
[2024-12-12T08:15:03.345+0000] {subprocess.py:93} INFO - [0m08:15:03    database: ecommerce
[2024-12-12T08:15:03.345+0000] {subprocess.py:93} INFO - [0m08:15:03    schema: oltp
[2024-12-12T08:15:03.346+0000] {subprocess.py:93} INFO - [0m08:15:03    connect_timeout: 10
[2024-12-12T08:15:03.346+0000] {subprocess.py:93} INFO - [0m08:15:03    role: None
[2024-12-12T08:15:03.347+0000] {subprocess.py:93} INFO - [0m08:15:03    search_path: None
[2024-12-12T08:15:03.347+0000] {subprocess.py:93} INFO - [0m08:15:03    keepalives_idle: 0
[2024-12-12T08:15:03.348+0000] {subprocess.py:93} INFO - [0m08:15:03    sslmode: None
[2024-12-12T08:15:03.348+0000] {subprocess.py:93} INFO - [0m08:15:03    sslcert: None
[2024-12-12T08:15:03.349+0000] {subprocess.py:93} INFO - [0m08:15:03    sslkey: None
[2024-12-12T08:15:03.350+0000] {subprocess.py:93} INFO - [0m08:15:03    sslrootcert: None
[2024-12-12T08:15:03.350+0000] {subprocess.py:93} INFO - [0m08:15:03    application_name: dbt
[2024-12-12T08:15:03.351+0000] {subprocess.py:93} INFO - [0m08:15:03    retries: 1
[2024-12-12T08:15:03.352+0000] {subprocess.py:93} INFO - [0m08:15:03  Registered adapter: postgres=1.8.0
[2024-12-12T08:15:03.509+0000] {subprocess.py:93} INFO - [0m08:15:03    Connection test: [[32mOK connection ok[0m]
[2024-12-12T08:15:03.510+0000] {subprocess.py:93} INFO - 
[2024-12-12T08:15:03.510+0000] {subprocess.py:93} INFO - [0m08:15:03  [32mAll checks passed![0m
[2024-12-12T08:15:04.399+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-12-12T08:15:04.400+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-12T08:15:04.426+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dbt_orchestrator, task_id=test_connection.dbt_test_connection, run_id=scheduled__2024-12-12T08:00:00+00:00, execution_date=20241212T080000, start_date=20241212T081500, end_date=20241212T081504
[2024-12-12T08:15:04.450+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-12-12T08:15:04.485+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-12T08:15:04.487+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
