[2024-12-12T08:06:50.984+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-12T08:06:51.012+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_orchestrator.test_connection.dbt_test_connection scheduled__2024-12-12T07:45:00+00:00 [queued]>
[2024-12-12T08:06:51.022+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_orchestrator.test_connection.dbt_test_connection scheduled__2024-12-12T07:45:00+00:00 [queued]>
[2024-12-12T08:06:51.022+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-12T08:06:51.037+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): test_connection.dbt_test_connection> on 2024-12-12 07:45:00+00:00
[2024-12-12T08:06:51.043+0000] {standard_task_runner.py:63} INFO - Started process 51 to run task
[2024-12-12T08:06:51.046+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_orchestrator', 'test_connection.dbt_test_connection', 'scheduled__2024-12-12T07:45:00+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp9v1lxru_']
[2024-12-12T08:06:51.048+0000] {standard_task_runner.py:91} INFO - Job 109: Subtask test_connection.dbt_test_connection
[2024-12-12T08:06:51.098+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_orchestrator.test_connection.dbt_test_connection scheduled__2024-12-12T07:45:00+00:00 [running]> on host 34fdc836a0bb
[2024-12-12T08:06:51.198+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ma7moud' AIRFLOW_CTX_DAG_ID='dbt_orchestrator' AIRFLOW_CTX_TASK_ID='test_connection.dbt_test_connection' AIRFLOW_CTX_EXECUTION_DATE='2024-12-12T07:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-12T07:45:00+00:00'
[2024-12-12T08:06:51.199+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-12T08:06:51.227+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-12T08:06:51.228+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt debug --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt/ecommerce']
[2024-12-12T08:06:51.240+0000] {subprocess.py:86} INFO - Output:
[2024-12-12T08:06:57.828+0000] {subprocess.py:93} INFO - [0m08:06:57  Running with dbt=1.8.0
[2024-12-12T08:06:57.927+0000] {subprocess.py:93} INFO - [0m08:06:57  dbt version: 1.8.0
[2024-12-12T08:06:57.928+0000] {subprocess.py:93} INFO - [0m08:06:57  python version: 3.9.19
[2024-12-12T08:06:57.928+0000] {subprocess.py:93} INFO - [0m08:06:57  python path: /home/***/.local/bin/python
[2024-12-12T08:06:57.929+0000] {subprocess.py:93} INFO - [0m08:06:57  os info: Linux-6.8.0-49-generic-x86_64-with-glibc2.36
[2024-12-12T08:06:58.003+0000] {subprocess.py:93} INFO - [0m08:06:58  Using profiles dir at /opt/***/dbt
[2024-12-12T08:06:58.003+0000] {subprocess.py:93} INFO - [0m08:06:58  Using profiles.yml file at /opt/***/dbt/profiles.yml
[2024-12-12T08:06:58.004+0000] {subprocess.py:93} INFO - [0m08:06:58  Using dbt_project.yml file at /opt/***/dbt/ecommerce/dbt_project.yml
[2024-12-12T08:06:58.005+0000] {subprocess.py:93} INFO - [0m08:06:58  adapter type: postgres
[2024-12-12T08:06:58.005+0000] {subprocess.py:93} INFO - [0m08:06:58  adapter version: 1.8.0
[2024-12-12T08:06:58.080+0000] {subprocess.py:93} INFO - [0m08:06:58  [[33mWARNING[0m]: Deprecated functionality
[2024-12-12T08:06:58.081+0000] {subprocess.py:93} INFO - The `tests` config has been renamed to `data_tests`. Please see
[2024-12-12T08:06:58.081+0000] {subprocess.py:93} INFO - https://docs.getdbt.com/docs/build/data-tests#new-data_tests-syntax for more
[2024-12-12T08:06:58.081+0000] {subprocess.py:93} INFO - information.
[2024-12-12T08:06:58.124+0000] {subprocess.py:93} INFO - [0m08:06:58  Configuration:
[2024-12-12T08:06:58.124+0000] {subprocess.py:93} INFO - [0m08:06:58    profiles.yml file [[32mOK found and valid[0m]
[2024-12-12T08:06:58.125+0000] {subprocess.py:93} INFO - [0m08:06:58    dbt_project.yml file [[32mOK found and valid[0m]
[2024-12-12T08:06:58.125+0000] {subprocess.py:93} INFO - [0m08:06:58  Required dependencies:
[2024-12-12T08:06:58.146+0000] {subprocess.py:93} INFO - [0m08:06:58   - git [[32mOK found[0m]
[2024-12-12T08:06:58.146+0000] {subprocess.py:93} INFO - 
[2024-12-12T08:06:58.146+0000] {subprocess.py:93} INFO - [0m08:06:58  Connection:
[2024-12-12T08:06:58.147+0000] {subprocess.py:93} INFO - [0m08:06:58    host: 172.18.0.3
[2024-12-12T08:06:58.148+0000] {subprocess.py:93} INFO - [0m08:06:58    port: 5432
[2024-12-12T08:06:58.149+0000] {subprocess.py:93} INFO - [0m08:06:58    user: ***
[2024-12-12T08:06:58.150+0000] {subprocess.py:93} INFO - [0m08:06:58    database: ecommerce
[2024-12-12T08:06:58.151+0000] {subprocess.py:93} INFO - [0m08:06:58    schema: oltp
[2024-12-12T08:06:58.151+0000] {subprocess.py:93} INFO - [0m08:06:58    connect_timeout: 10
[2024-12-12T08:06:58.152+0000] {subprocess.py:93} INFO - [0m08:06:58    role: None
[2024-12-12T08:06:58.153+0000] {subprocess.py:93} INFO - [0m08:06:58    search_path: None
[2024-12-12T08:06:58.154+0000] {subprocess.py:93} INFO - [0m08:06:58    keepalives_idle: 0
[2024-12-12T08:06:58.155+0000] {subprocess.py:93} INFO - [0m08:06:58    sslmode: None
[2024-12-12T08:06:58.156+0000] {subprocess.py:93} INFO - [0m08:06:58    sslcert: None
[2024-12-12T08:06:58.156+0000] {subprocess.py:93} INFO - [0m08:06:58    sslkey: None
[2024-12-12T08:06:58.157+0000] {subprocess.py:93} INFO - [0m08:06:58    sslrootcert: None
[2024-12-12T08:06:58.158+0000] {subprocess.py:93} INFO - [0m08:06:58    application_name: dbt
[2024-12-12T08:06:58.159+0000] {subprocess.py:93} INFO - [0m08:06:58    retries: 1
[2024-12-12T08:06:58.160+0000] {subprocess.py:93} INFO - [0m08:06:58  Registered adapter: postgres=1.8.0
[2024-12-12T08:06:58.336+0000] {subprocess.py:93} INFO - [0m08:06:58    Connection test: [[32mOK connection ok[0m]
[2024-12-12T08:06:58.336+0000] {subprocess.py:93} INFO - 
[2024-12-12T08:06:58.336+0000] {subprocess.py:93} INFO - [0m08:06:58  [32mAll checks passed![0m
[2024-12-12T08:06:59.293+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-12-12T08:06:59.293+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-12T08:06:59.348+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dbt_orchestrator, task_id=test_connection.dbt_test_connection, run_id=scheduled__2024-12-12T07:45:00+00:00, execution_date=20241212T074500, start_date=20241212T080651, end_date=20241212T080659
[2024-12-12T08:06:59.442+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-12-12T08:06:59.477+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-12T08:06:59.509+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
